general {
    hide_cursor = false
}

background {
    monitor =
    path = /home/diego/.wallpapers/1.jpg
    blur_passes = 2
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgb(c0caf5)
    check_color = rgb(9ece6a)
    fail_color = rgb(f7768e)

    font_color = rgb(c0caf5)
    fade_on_empty = false
    rounding = 15

    font_family = JetBrainsMono Nerd Font
    placeholder_text = Input password...
    fail_text = Try Again...

    position = 0, -20
    halign = center
    valign = center
}