general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    path = /home/diego/.wallpapers/1.png
    blur_passes = 2
}

input-field {
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0)

    outer_color = rgb(A9B1D6)
    check_color = rgb(98971a)
    fail_color = rga(cc241d)

    font_color = rgb(ebdbb2)
    fade_on_empty = false
    rounding = 15

    placeholder_text = Input password...
    fail_text = Try again... 

    dots_spacing = 0.3

    position = 0, -20
    halign = center
    valign = center
}